# Licensed Materials - Property of IBM
# IBM Transformation Extender Advanced (5724-Q23)
# (C) Copyright IBM Corp. 2021, 2022 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
{{- include "itxa-chart.licenseValidate" . | required "License must be accepted by setting license key to true" }}
{{ if .Values.global.install.itxaUI.enabled -}}
{{- if gt .Values.itxauiserver.replicaCount 0.0 }}
{{- include "sch.config.init" (list . "itxa-chart.sch.chart.config.values") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "itxa-chart.fullname" . }}-itxauiserver
  labels:
{{ include "sch.metadata.labels.standard" (list .) | indent 4 }}
spec:
  {{- if eq .Values.itxauiserver.ingress.enabled false }}
  type: {{ .Values.itxauiserver.service.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.itxauiserver.service.http.port | default 9081 }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.itxauiserver.ingress.enabled false }}
      nodePort: {{ .Values.itxauiserver.service.http.nodePort }}
      {{- end }}
    - port: {{ .Values.itxauiserver.service.https.port | default 9444 }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if eq .Values.itxauiserver.ingress.enabled false }}
      nodePort: {{ .Values.itxauiserver.service.https.nodePort }}
      {{- end }}
  selector:
{{ include "sch.metadata.labels.standard" (list . "" (dict "role" "itxauiserver")) | indent 4 }}
{{- end }}
{{ end -}}