apiVersion: v1
kind: PersistentVolume
metadata:
  name: itxa-pv
  labels:
    intent: itxa-logs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 12Gi
  nfs:
    path: /shared/nfs
    server: my.nfs.server.com
  persistentVolumeReclaimPolicy: Retain
  storageClassName: itxa-sc
status: {}
