# Licensed Materials - Property of IBM
# IBM Transformation Extender Advanced (5724-Q23)
# (C) Copyright IBM Corp. 2021, 2023 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
apiVersion: v1
kind: Secret
metadata:
  name: itxa-db-secrets
type: Opaque
stringData:
  #For Oracle, the value of parameter 'databaseName' should be either the SID or the service name. 
  databaseName: dbname
  dbUser: dbuser
  dbPassword: password
  dbHostIp: "X.XX.XXX.XXX"
  dbPort: "dbport"
  accessKey: "<S3Host_accesskey>"
  secretKey: "<S3Host_secretkey>"
  #The following dbCurrentSchema parameter is added to mention schema name for DB2(schema name should be in CAPS).
  dbCurrentSchema: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-keystore-secret
type: Opaque
stringData:
  tlskeystorepassword: password

---
apiVersion: v1
kind: Secret
metadata:
  name: itxa-user-secret
type: Opaque
stringData:
  adminPassword: "<password_for_admin_user>" 
